ALTER TABLE "award_categories" ADD COLUMN "category_group" text DEFAULT 'premier' NOT NULL;
--> statement-breakpoint
ALTER TABLE "award_categories" ADD COLUMN "eligibility" text DEFAULT 'current_year' NOT NULL;
--> statement-breakpoint
ALTER TABLE "award_categories" ADD COLUMN "allow_editions" boolean DEFAULT false NOT NULL;
--> statement-breakpoint
ALTER TABLE "award_categories" ADD CONSTRAINT "award_categories_eligibility_check" CHECK ("eligibility" IN ('current_year', 'current_or_active', 'active_in_year', 'upcoming', 'any_year'));
--> statement-breakpoint
INSERT INTO "award_categories" ("id", "label", "description", "sort_order", "active", "category_group", "eligibility", "allow_editions") VALUES
  ('best-game-design', 'Best Game Design', NULL, 2, true, 'premier', 'current_year', false),
  ('narrative', 'Best Story', NULL, 3, true, 'premier', 'current_year', false),
  ('art-direction', 'Best Art Direction', NULL, 4, true, 'premier', 'current_year', false),
  ('soundtrack', 'Best Soundtrack', NULL, 5, true, 'premier', 'current_year', false),
  ('best-audio-design', 'Best Audio Design', NULL, 6, true, 'premier', 'current_year', false),
  ('indie', 'Best Indie Game', NULL, 7, true, 'major', 'current_year', false),
  ('best-multiplayer', 'Best Multiplayer', NULL, 8, true, 'major', 'current_or_active', false),
  ('best-ongoing-game', 'Best Ongoing Game', NULL, 9, true, 'major', 'active_in_year', false),
  ('best-action-adventure', 'Best Action / Adventure', NULL, 10, true, 'genre', 'current_year', false),
  ('best-rpg', 'Best RPG', NULL, 11, true, 'genre', 'current_year', false),
  ('best-action-game', 'Best Action Game', NULL, 12, true, 'genre', 'current_year', false),
  ('best-fighting-game', 'Best Fighting Game', NULL, 13, true, 'genre', 'current_year', false),
  ('best-sim-strategy', 'Best Sim / Strategy', NULL, 14, true, 'genre', 'current_year', false),
  ('best-sports-racing', 'Best Sports / Racing', NULL, 15, true, 'genre', 'current_year', false),
  ('best-family-game', 'Best Family Game', NULL, 16, true, 'genre', 'current_year', false),
  ('best-debut-indie', 'Best Debut Indie', NULL, 17, true, 'major', 'current_year', false),
  ('best-mobile-game', 'Best Mobile Game', NULL, 18, true, 'platform', 'current_year', false),
  ('best-vr-ar-game', 'Best VR / AR Game', NULL, 19, true, 'platform', 'current_year', false),
  ('best-accessibility', 'Best Accessibility', NULL, 20, true, 'craft', 'current_or_active', false),
  ('most-anticipated-game', 'Most Anticipated Game', NULL, 21, true, 'special', 'upcoming', false),
  ('best-remake-remaster', 'Best Remake / Remaster', NULL, 22, true, 'special', 'current_year', true),
  ('best-expansion-dlc', 'Best Expansion / DLC', NULL, 23, true, 'special', 'current_year', true),
  ('best-new-ip', 'Best New IP', NULL, 24, true, 'special', 'current_year', false),
  ('best-combat', 'Best Combat', NULL, 25, true, 'gameplay', 'current_year', false),
  ('best-boss-battles', 'Best Boss Battles', NULL, 26, true, 'gameplay', 'current_year', false),
  ('best-melee-combat', 'Best Melee Combat', NULL, 27, true, 'gameplay', 'current_year', false),
  ('best-gunplay', 'Best Gunplay', NULL, 28, true, 'gameplay', 'current_year', false),
  ('best-parry-system', 'Best Parry System', NULL, 29, true, 'gameplay', 'current_year', false),
  ('best-magic-system', 'Best Magic System', NULL, 30, true, 'gameplay', 'current_year', false),
  ('best-stealth', 'Best Stealth', NULL, 31, true, 'gameplay', 'current_year', false),
  ('best-enemy-design', 'Best Enemy Design', NULL, 32, true, 'gameplay', 'current_year', false),
  ('best-difficulty-design', 'Best Difficulty Design', NULL, 33, true, 'gameplay', 'current_year', false),
  ('best-movement', 'Best Movement', NULL, 34, true, 'gameplay', 'current_year', false),
  ('best-traversal', 'Best Traversal', NULL, 35, true, 'gameplay', 'current_year', false),
  ('best-exploration', 'Best Exploration', NULL, 36, true, 'gameplay', 'current_year', false),
  ('best-level-design', 'Best Level Design', NULL, 37, true, 'design', 'current_year', false),
  ('best-open-world', 'Best Open World', NULL, 38, true, 'design', 'current_year', false),
  ('best-worldbuilding', 'Best Worldbuilding', NULL, 39, true, 'design', 'current_year', false),
  ('best-buildcrafting', 'Best Buildcrafting', NULL, 40, true, 'systems', 'current_year', false),
  ('best-progression-system', 'Best Progression System', NULL, 41, true, 'systems', 'current_year', false),
  ('best-loot-system', 'Best Loot System', NULL, 42, true, 'systems', 'current_year', false),
  ('best-crafting-system', 'Best Crafting System', NULL, 43, true, 'systems', 'current_year', false),
  ('best-character-creator', 'Best Character Creator', NULL, 44, true, 'systems', 'current_year', false),
  ('best-customization', 'Best Customization', NULL, 45, true, 'systems', 'current_year', false),
  ('best-physics', 'Best Physics', NULL, 46, true, 'technical', 'current_year', false),
  ('best-destruction', 'Best Destruction', NULL, 47, true, 'technical', 'current_year', false),
  ('best-ai', 'Best AI', NULL, 48, true, 'technical', 'current_year', false),
  ('best-puzzle-design', 'Best Puzzle Design', NULL, 49, true, 'gameplay', 'current_year', false),
  ('best-ui-ux', 'Best UI / UX', NULL, 50, true, 'technical', 'current_year', false),
  ('best-co-op', 'Best Co-op', NULL, 51, true, 'multiplayer', 'current_or_active', false),
  ('best-pvp', 'Best PvP', NULL, 52, true, 'multiplayer', 'current_or_active', false),
  ('biggest-surprise', 'Biggest Surprise', NULL, 53, true, 'fun', 'current_year', false),
  ('biggest-disappointment', 'Biggest Disappointment', NULL, 54, true, 'fun', 'current_year', false),
  ('most-underrated', 'Most Underrated', NULL, 55, true, 'fun', 'current_year', false),
  ('most-innovative', 'Most Innovative', NULL, 56, true, 'fun', 'current_year', false),
  ('funniest-game', 'Funniest Game', NULL, 57, true, 'fun', 'current_year', false),
  ('scariest-game', 'Scariest Game', NULL, 58, true, 'fun', 'current_year', false),
  ('most-emotional-game', 'Most Emotional Game', NULL, 59, true, 'fun', 'current_year', false),
  ('best-game-you-finally-played', 'Best Game You Finally Played', NULL, 60, true, 'community', 'any_year', false),
  ('wish-i-played', 'Wish I Played', NULL, 61, true, 'community', 'current_year', false),
  ('best-game-to-play-with-friends', 'Best Game to Play With Friends', NULL, 62, true, 'community', 'current_or_active', false),
  ('best-game-to-watch', 'Best Game to Watch', NULL, 63, true, 'community', 'current_or_active', false),
  ('best-one-more-run-game', 'Best "One More Run" Game', NULL, 64, true, 'community', 'current_year', false)
ON CONFLICT ("id") DO UPDATE SET
  "label" = EXCLUDED."label",
  "sort_order" = EXCLUDED."sort_order",
  "active" = true,
  "category_group" = EXCLUDED."category_group",
  "eligibility" = EXCLUDED."eligibility",
  "allow_editions" = EXCLUDED."allow_editions";
--> statement-breakpoint
UPDATE "award_categories" SET "active" = false
WHERE "id" NOT IN (
  'best-game-design', 'narrative', 'art-direction', 'soundtrack', 'best-audio-design',
  'indie', 'best-multiplayer', 'best-ongoing-game', 'best-action-adventure', 'best-rpg',
  'best-action-game', 'best-fighting-game', 'best-sim-strategy', 'best-sports-racing',
  'best-family-game', 'best-debut-indie', 'best-mobile-game', 'best-vr-ar-game',
  'best-accessibility', 'most-anticipated-game', 'best-remake-remaster', 'best-expansion-dlc',
  'best-new-ip', 'best-combat', 'best-boss-battles', 'best-melee-combat', 'best-gunplay',
  'best-parry-system', 'best-magic-system', 'best-stealth', 'best-enemy-design',
  'best-difficulty-design', 'best-movement', 'best-traversal', 'best-exploration',
  'best-level-design', 'best-open-world', 'best-worldbuilding', 'best-buildcrafting',
  'best-progression-system', 'best-loot-system', 'best-crafting-system',
  'best-character-creator', 'best-customization', 'best-physics', 'best-destruction',
  'best-ai', 'best-puzzle-design', 'best-ui-ux', 'best-co-op', 'best-pvp',
  'biggest-surprise', 'biggest-disappointment', 'most-underrated', 'most-innovative',
  'funniest-game', 'scariest-game', 'most-emotional-game', 'best-game-you-finally-played',
  'wish-i-played', 'best-game-to-play-with-friends', 'best-game-to-watch',
  'best-one-more-run-game'
);
