INSERT INTO "award_categories" ("id", "label", "description", "sort_order", "active", "category_group", "eligibility", "allow_editions") VALUES
  ('best-game-design', 'Best Game Design', 'Where mechanics, systems, and ideas come together beautifully.', 2, true, 'premier', 'current_year', false),
  ('narrative', 'Best Story', 'The story you couldn''t stop thinking about.', 3, true, 'premier', 'current_year', false),
  ('art-direction', 'Best Art Direction', 'A world with a look all its own.', 4, true, 'premier', 'current_year', false),
  ('soundtrack', 'Best Soundtrack', 'The music that stayed with you after you stopped playing.', 5, true, 'premier', 'current_year', false),
  ('best-audio-design', 'Best Audio Design', 'Every hit, footstep, explosion, and quiet moment sounds just right.', 6, true, 'premier', 'current_year', false),
  ('indie', 'Best Indie Game', 'A smaller production that made a huge impression.', 7, true, 'major', 'current_year', false),
  ('best-debut-indie', 'Best Debut Indie', 'An unforgettable first showing from a new studio.', 8, true, 'major', 'current_year', false),
  ('best-new-ip', 'Best New IP', 'The best brand-new world, idea, or franchise.', 9, true, 'major', 'current_year', false),
  ('best-ongoing-game', 'Best Ongoing Game', 'Still giving you reasons to come back.', 10, true, 'major', 'active_in_year', false),
  ('best-multiplayer', 'Best Multiplayer', 'Better because you''re playing with—or against—someone else.', 11, true, 'major', 'current_or_active', false),
  ('best-mobile-game', 'Best Mobile Game', 'The best game made for your pocket.', 12, true, 'platform', 'current_year', false),
  ('best-vr-ar-game', 'Best VR / AR Game', 'The experience that made stepping inside the game worth it.', 13, true, 'platform', 'current_year', false),
  ('best-remake-remaster', 'Best Remake / Remaster', 'An old favorite made worth playing all over again.', 14, true, 'special', 'current_year', true),
  ('best-expansion-dlc', 'Best Expansion / DLC', 'The add-on that gave you a reason to jump back in.', 15, true, 'special', 'current_year', true),
  ('most-anticipated-game', 'Most Anticipated Game', 'The game you need to play next.', 16, true, 'special', 'upcoming', false),
  ('best-action-adventure', 'Best Action / Adventure', 'Exploration, action, and adventure at their best.', 17, true, 'genre', 'current_year', false),
  ('best-rpg', 'Best RPG', 'The adventure where your character, choices, and progression mattered most.', 18, true, 'genre', 'current_year', false),
  ('best-action-game', 'Best Action Game', 'Pure action that just feels great to play.', 19, true, 'genre', 'current_year', false),
  ('best-fighting-game', 'Best Fighting Game', 'The best game for settling things one round at a time.', 20, true, 'genre', 'current_year', false),
  ('best-sim-strategy', 'Best Sim / Strategy', 'The game that made every decision count.', 21, true, 'genre', 'current_year', false),
  ('best-sports-racing', 'Best Sports / Racing', 'The best competition on the field, court, track, or road.', 22, true, 'genre', 'current_year', false),
  ('best-family-game', 'Best Family Game', 'The game everyone can get in on.', 23, true, 'genre', 'current_year', false),
  ('best-platformer', 'Best Platformer', 'Jumping, climbing, bouncing, and falling done right.', 24, true, 'genre', 'current_year', false),
  ('best-puzzle-game', 'Best Puzzle Game', 'The one that made being stuck feel worth it.', 25, true, 'genre', 'current_year', false),
  ('best-horror-game', 'Best Horror Game', 'The game you maybe shouldn''t have played with the lights off.', 26, true, 'genre', 'current_year', false),
  ('best-survival-game', 'Best Survival Game', 'When simply staying alive is half the fun.', 27, true, 'genre', 'current_year', false),
  ('best-roguelike-roguelite', 'Best Roguelike / Roguelite', 'Just one more run. Okay, maybe five.', 28, true, 'genre', 'current_year', false),
  ('best-metroidvania', 'Best Metroidvania', 'Getting lost has never felt so rewarding.', 29, true, 'genre', 'current_year', false),
  ('best-cozy-game', 'Best Cozy Game', 'The gaming equivalent of a warm blanket.', 30, true, 'genre', 'current_year', false),
  ('best-party-game', 'Best Party Game', 'The game that gets everyone yelling at the screen.', 31, true, 'genre', 'current_year', false),
  ('best-combat', 'Best Combat', 'Fighting so good you look forward to the next encounter.', 32, true, 'gameplay', 'current_year', false),
  ('best-melee-combat', 'Best Melee Combat', 'Up close and personal—and incredibly satisfying.', 33, true, 'gameplay', 'current_year', false),
  ('best-gunplay', 'Best Gunplay', 'Every shot just feels right.', 34, true, 'gameplay', 'current_year', false),
  ('best-parry-system', 'Best Parry System', 'That perfect clang that makes you feel unstoppable.', 35, true, 'gameplay', 'current_year', false),
  ('best-dodge-dash', 'Best Dodge / Dash', 'Getting out of the way is half the fun.', 36, true, 'gameplay', 'current_year', false),
  ('best-magic-system', 'Best Magic System', 'The game that made casting spells feel truly powerful.', 37, true, 'gameplay', 'current_year', false),
  ('best-stealth', 'Best Stealth', 'Getting in and out without anyone knowing you were there.', 38, true, 'gameplay', 'current_year', false),
  ('best-boss-battles', 'Best Boss Battles', 'The fights you''ll still be talking about years later.', 39, true, 'gameplay', 'current_year', false),
  ('best-enemy-design', 'Best Enemy Design', 'Enemies that made every encounter interesting.', 40, true, 'gameplay', 'current_year', false),
  ('best-difficulty-design', 'Best Difficulty Design', 'Tough enough to test you, fair enough to keep you trying.', 41, true, 'gameplay', 'current_year', false),
  ('best-movement', 'Best Movement', 'Simply controlling your character feels incredible.', 42, true, 'gameplay', 'current_year', false),
  ('best-traversal', 'Best Traversal', 'Getting there is just as fun as being there.', 43, true, 'gameplay', 'current_year', false),
  ('best-exploration', 'Best Exploration', 'The game that always rewarded taking the long way around.', 44, true, 'gameplay', 'current_year', false),
  ('best-level-design', 'Best Level Design', 'Every room, path, shortcut, and secret feels deliberately placed.', 45, true, 'design', 'current_year', false),
  ('best-open-world', 'Best Open World', 'A world worth ignoring the main quest for.', 46, true, 'design', 'current_year', false),
  ('best-worldbuilding', 'Best Worldbuilding', 'A place that feels like it existed before you arrived.', 47, true, 'design', 'current_year', false),
  ('best-buildcrafting', 'Best Buildcrafting', 'Half the game is playing. The other half is perfecting your build.', 48, true, 'systems', 'current_year', false),
  ('best-progression-system', 'Best Progression System', 'Getting stronger never stopped feeling rewarding.', 49, true, 'systems', 'current_year', false),
  ('best-skill-tree', 'Best Skill Tree', 'Every point spent comes with a difficult decision.', 50, true, 'systems', 'current_year', false),
  ('best-loot-system', 'Best Loot System', 'Always chasing that next drop.', 51, true, 'systems', 'current_year', false),
  ('best-crafting-system', 'Best Crafting System', 'Turning a pile of stuff into something you actually want.', 52, true, 'systems', 'current_year', false),
  ('best-character-creator', 'Best Character Creator', 'Where "I''ll just make my character real quick" becomes an hour.', 53, true, 'systems', 'current_year', false),
  ('best-customization', 'Best Customization', 'The game that really lets you make it yours.', 54, true, 'systems', 'current_year', false),
  ('best-inventory-system', 'Best Inventory System', 'Somehow, managing all your stuff is actually enjoyable.', 55, true, 'systems', 'current_year', false),
  ('best-economy', 'Best Economy', 'Buying, selling, earning, and spending that actually works.', 56, true, 'systems', 'current_year', false),
  ('best-endgame', 'Best Endgame', 'The credits rolled. You kept playing.', 57, true, 'systems', 'current_year', false),
  ('best-new-game-plus', 'Best New Game+', 'Because once wasn''t enough.', 58, true, 'systems', 'current_year', false),
  ('best-physics', 'Best Physics', 'When the game''s rules create their own kind of fun.', 59, true, 'technical', 'current_year', false),
  ('best-destruction', 'Best Destruction', 'If it''s there, you should probably be able to break it.', 60, true, 'technical', 'current_year', false),
  ('best-ai', 'Best AI', 'Enemies and characters that actually seem to know what they''re doing.', 61, true, 'technical', 'current_year', false),
  ('best-procedural-generation', 'Best Procedural Generation', 'A game that keeps finding new ways to surprise you.', 62, true, 'technical', 'current_year', false),
  ('best-puzzle-design', 'Best Puzzle Design', 'The best "wait... I got it!" moments of the year.', 63, true, 'gameplay', 'current_year', false),
  ('best-tutorial-onboarding', 'Best Tutorial / Onboarding', 'Teaching you how to play without feeling like homework.', 64, true, 'technical', 'current_year', false),
  ('best-ui-ux', 'Best UI / UX', 'Everything is exactly where you expect it to be.', 65, true, 'technical', 'current_year', false),
  ('best-accessibility', 'Best Accessibility', 'More ways for more people to play.', 66, true, 'craft', 'current_or_active', false),
  ('best-photo-mode', 'Best Photo Mode', 'Sometimes playing the game means stopping to take pictures.', 67, true, 'craft', 'current_year', false),
  ('best-co-op', 'Best Co-op', 'The game you want a friend beside you for.', 68, true, 'multiplayer', 'current_or_active', false),
  ('best-pvp', 'Best PvP', 'Nothing beats outplaying another human.', 69, true, 'multiplayer', 'current_or_active', false),
  ('best-local-multiplayer', 'Best Local Multiplayer', 'Same game. Same couch. Questionable friendships afterward.', 70, true, 'multiplayer', 'current_or_active', false),
  ('best-social-mechanics', 'Best Social Mechanics', 'The game that found clever ways to bring players together.', 71, true, 'multiplayer', 'current_or_active', false),
  ('best-multiplayer-progression', 'Best Multiplayer Progression', 'Always one more unlock worth chasing.', 72, true, 'multiplayer', 'current_or_active', false),
  ('biggest-surprise', 'Biggest Surprise', 'You expected little. You got something special.', 73, true, 'fun', 'current_year', false),
  ('biggest-disappointment', 'Biggest Disappointment', 'You wanted to love it. You really did.', 74, true, 'fun', 'current_year', false),
  ('most-underrated', 'Most Underrated', 'More people should be talking about this game.', 75, true, 'fun', 'current_year', false),
  ('most-innovative', 'Most Innovative', 'The game that tried something genuinely different.', 76, true, 'fun', 'current_year', false),
  ('funniest-game', 'Funniest Game', 'The game that actually made you laugh.', 77, true, 'fun', 'current_year', false),
  ('scariest-game', 'Scariest Game', 'Nope. Nope. Nope.', 78, true, 'fun', 'current_year', false),
  ('most-emotional-game', 'Most Emotional Game', 'The one that hit you harder than expected.', 79, true, 'fun', 'current_year', false),
  ('most-relaxing-game', 'Most Relaxing Game', 'No stress. No rush. Just a good time.', 80, true, 'fun', 'current_year', false),
  ('most-addictive', 'Most Addictive', 'You were going to stop an hour ago.', 81, true, 'fun', 'current_year', false),
  ('best-replayability', 'Best Replayability', 'Finishing it just made you want to start again.', 82, true, 'fun', 'current_year', false),
  ('best-game-to-play-with-friends', 'Best Game to Play With Friends', 'Everything''s better with the group.', 83, true, 'community', 'current_or_active', false),
  ('best-game-to-watch', 'Best Game to Watch', 'Almost as much fun to watch as it is to play.', 84, true, 'community', 'current_or_active', false),
  ('best-one-more-run-game', 'Best “One More Run” Game', 'You know exactly what "one more" actually means.', 85, true, 'community', 'current_year', false),
  ('best-game-you-finally-played', 'Best Game You Finally Played', 'Better late than never.', 86, true, 'community', 'any_year', false),
  ('wish-i-played', 'Wish I Played', 'The one everyone loved while your backlog quietly judged you.', 87, true, 'community', 'current_year', false)
ON CONFLICT ("id") DO UPDATE SET
  "label" = EXCLUDED."label",
  "description" = EXCLUDED."description",
  "sort_order" = EXCLUDED."sort_order",
  "active" = true,
  "category_group" = EXCLUDED."category_group",
  "eligibility" = EXCLUDED."eligibility",
  "allow_editions" = EXCLUDED."allow_editions";
--> statement-breakpoint
UPDATE "award_categories" SET "active" = false
WHERE "id" NOT IN ('best-game-design', 'narrative', 'art-direction', 'soundtrack', 'best-audio-design', 'indie', 'best-debut-indie', 'best-new-ip', 'best-ongoing-game', 'best-multiplayer', 'best-mobile-game', 'best-vr-ar-game', 'best-remake-remaster', 'best-expansion-dlc', 'most-anticipated-game', 'best-action-adventure', 'best-rpg', 'best-action-game', 'best-fighting-game', 'best-sim-strategy', 'best-sports-racing', 'best-family-game', 'best-platformer', 'best-puzzle-game', 'best-horror-game', 'best-survival-game', 'best-roguelike-roguelite', 'best-metroidvania', 'best-cozy-game', 'best-party-game', 'best-combat', 'best-melee-combat', 'best-gunplay', 'best-parry-system', 'best-dodge-dash', 'best-magic-system', 'best-stealth', 'best-boss-battles', 'best-enemy-design', 'best-difficulty-design', 'best-movement', 'best-traversal', 'best-exploration', 'best-level-design', 'best-open-world', 'best-worldbuilding', 'best-buildcrafting', 'best-progression-system', 'best-skill-tree', 'best-loot-system', 'best-crafting-system', 'best-character-creator', 'best-customization', 'best-inventory-system', 'best-economy', 'best-endgame', 'best-new-game-plus', 'best-physics', 'best-destruction', 'best-ai', 'best-procedural-generation', 'best-puzzle-design', 'best-tutorial-onboarding', 'best-ui-ux', 'best-accessibility', 'best-photo-mode', 'best-co-op', 'best-pvp', 'best-local-multiplayer', 'best-social-mechanics', 'best-multiplayer-progression', 'biggest-surprise', 'biggest-disappointment', 'most-underrated', 'most-innovative', 'funniest-game', 'scariest-game', 'most-emotional-game', 'most-relaxing-game', 'most-addictive', 'best-replayability', 'best-game-to-play-with-friends', 'best-game-to-watch', 'best-one-more-run-game', 'best-game-you-finally-played', 'wish-i-played');
